public class FindDiv {
    /* 找到可以被整除的数
- 取模运算：整数的取模运算
- 布尔运算：==操作符
- 自增运算
     */
    public static void main(String[] args) {
        int dividend = 35;
        int divisor = 9;
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
        System.out.println(dividend + "可以整除" + divisor + "吗？" + ((dividend++) % divisor == 0));
    }
}
